# Web Scraping the Earnings Calender

In [651]:
import pandas as pd
from datetime import datetime
from datetime import timedelta
from yahoo_earnings_calendar import YahooEarningsCalendar
import dateutil.parser

In [652]:
# setting the report date
report_date = datetime.now().date()

# downloading the earnings calendar
yec = YahooEarningsCalendar()
earnings_list = yec.earnings_on(report_date)

# saving the data in a pandas DataFrame
earnings_df = pd.DataFrame(earnings_list)
earnings_df.head()

Empty DataFrame
Columns: []
Index: []

### Earnings Announcements in the next 7 Days

In [653]:
DAYS_AHEAD = 7

# setting the dates
start_date = datetime.now().date()
end_date = (datetime.now().date() + timedelta(days=DAYS_AHEAD))

# downloading the earnings calendar
yec = YahooEarningsCalendar()
earnings_list = yec.earnings_between(start_date, end_date)

# saving the data in a pandas DataFrame
earnings_df = pd.DataFrame(earnings_list)
earnings_df.head()

,ticker,companyshortname,startdatetime,startdatetimetype,epsestimate,epsactual,epssurprisepct,timeZoneShortName,gmtOffsetMilliSeconds,quoteType
0,AMPE,Ampio Pharmaceuticals Inc,2021-02-15T13:30:00.000Z,BMO,nan,None,None,EST,-18000000,EQUITY
1,RYCFF,Amira Nature Foods Ltd,2021-02-15T13:30:00.000Z,BMO,nan,None,None,EDT,-14400000,EQUITY
2,ANFIF,Amira Nature Foods Ltd,2021-02-15T13:30:00.000Z,BMO,nan,None,None,EST,-18000000,EQUITY
3,SB,Safe Bulkers Inc,2021-02-15T21:00:00.000Z,AMC,0,None,None,EST,-18000000,EQUITY
4,OCN,Ocwen Financial Corp,2021-02-15T21:00:00.000Z,AMC,0,None,None,EST,-18000000,EQUITY

#### Get Historical Earnings

In [668]:
# setting the parameters 
TICKER = 'AMD'
DAYS_ = 2400

# setting the dates
end_date = datetime.now().date()
start_date = (datetime.now().date() - timedelta(days=DAYS_))

# downloading the earnings calendar
yec = YahooEarningsCalendar()
earnings_list = yec.get_earnings_of(TICKER)
earnings_df = pd.DataFrame(earnings_list)

# extracting the date from the string and filtering for the period of interest
earnings_df['report_date'] = earnings_df['startdatetime'].apply(lambda x: dateutil.parser.isoparse(x).date())
earnings_df = earnings_df.loc[earnings_df['report_date'].between(start_date, end_date)] \
                         .sort_values('report_date')

earnings_df

,ticker,companyshortname,startdatetime,startdatetimetype,epsestimate,epsactual,epssurprisepct,timeZoneShortName,gmtOffsetMilliSeconds,quoteType,report_date
29,AMD,"Advanced Micro Devices, Inc.",2014-10-16T00:00:00.000Z,TNS,0,0,-29,EST,0,EQUITY,2014-10-16
28,AMD,"Advanced Micro Devices, Inc.",2015-01-20T00:00:00.000Z,TNS,0,0,-100,EST,0,EQUITY,2015-01-20
27,AMD,"Advanced Micro Devices, Inc.",2015-04-16T00:00:00.000Z,TNS,-0,-0,-73,EST,0,EQUITY,2015-04-16
26,AMD,"Advanced Micro Devices, Inc.",2015-07-16T00:00:00.000Z,TNS,-0,-0,-2,EST,0,EQUITY,2015-07-16
25,AMD,"Advanced Micro Devices, Inc.",2015-10-15T00:00:00.000Z,TNS,-0,-0,-47,EST,0,EQUITY,2015-10-15
24,AMD,"Advanced Micro Devices, Inc.",2016-01-19T00:00:00.000Z,TNS,-0,-0,1,EST,0,EQUITY,2016-01-19
23,AMD,"Advanced Micro Devices, Inc.",2016-04-21T00:00:00.000Z,TNS,-0,-0,6,EST,0,EQUITY,2016-04-21
22,AMD,"Advanced Micro Devices, Inc.",2016-07-21T00:00:00.000Z,TNS,-0,-0,40,EST,0,EQUITY,2016-07-21
21,AMD,"Advanced Micro Devices, Inc.",2016-10-20T00:00:00.000Z,TNS,0,0,650,EST,0,EQUITY,2016-10-20
20,AMD,"Advanced Micro Devices, Inc.",2017-01-31T00:00:00.000Z,TNS,-0,-0,38,EST,0,EQUITY,2017-01-31
19,AMD,"Advanced Micro Devices, Inc.",2017-05-01T00:00:00.000Z,TNS,-0,-0,5,EST,0,EQUITY,2017-05-01
18,AMD,"Advanced Micro Devices, Inc.",2017-07-25T00:00:00.000Z,TNS,0,0,nan,EST,0,EQUITY,2017-07-25
17,AMD,"Advanced Micro Devices, Inc.",2017-10-24T00:00:00.000Z,TNS,0,0,32,EST,0,EQUITY,2017-10-24
16,AMD,"Advanced Micro Devices, Inc.",2018-01-30T00:00:00.000Z,TNS,0,0,63,EST,0,EQUITY,2018-01-30
15,AMD,"Advanced Micro Devices, Inc.",2018-04-25T00:00:00.000Z,TNS,0,0,24,EST,0,EQUITY,2018-04-25
14,AMD,"Advanced Micro Devices, Inc.",2018-07-25T00:00:00.000Z,TNS,0,0,12,EST,0,EQUITY,2018-07-25
13,AMD,"Advanced Micro Devices, Inc.",2018-10-24T00:00:00.000Z,TNS,0,0,5,EST,0,EQUITY,2018-10-24
12,AMD,"Advanced Micro Devices, Inc.",2019-01-29T00:00:00.000Z,TNS,0,0,-2,EST,0,EQUITY,2019-01-29
11,AMD,"Advanced Micro Devices, Inc.",2019-04-30T00:00:00.000Z,TNS,0,0,18,EST,0,EQUITY,2019-04-30
10,AMD,"Advanced Micro Devices, Inc.",2019-07-30T00:00:00.000Z,TNS,0,0,4,EST,0,EQUITY,2019-07-30
9,AMD,"Advanced Micro Devices, Inc.",2019-10-29T00:00:00.000Z,TNS,0,0,-2,EST,0,EQUITY,2019-10-29
8,AMD,"Advanced Micro Devices, Inc.",2020-01-28T00:00:00.000Z,TNS,0,0,4,EST,0,EQUITY,2020-01-28
7,AMD,"Advanced Micro Devices, Inc.",2020-04-28T00:00:00.000Z,TNS,0,0,0,EST,0,EQUITY,2020-04-28
6,AMD,"Advanced Micro Devices, Inc.",2020-07-28T00:00:00.000Z,TNS,0,0,10,EST,0,EQUITY,2020-07-28
5,AMD,"Advanced Micro Devices, Inc.",2020-10-27T00:00:00.000Z,TNS,0,0,15,EST,0,EQUITY,2020-10-27
4,AMD,"Advanced Micro Devices, Inc.",2021-01-26T00:00:00.000Z,TNS,0,1,10,EST,0,EQUITY,2021-01-26

###  The Announcement Dates

In [671]:
len(earnings_df)

26

In [669]:
Num = list('A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z')

In [670]:
len(Num)

26

In [672]:
events = earnings_df.report_date.tolist()
data = {'Number':Num, 'Events':events } 
event_df = pd.DataFrame(data)

In [675]:
event_df

   Number      Events
0       A  2014-10-16
1       B  2015-01-20
2       C  2015-04-16
3       D  2015-07-16
4       E  2015-10-15
5       F  2016-01-19
6       G  2016-04-21
7       H  2016-07-21
8       I  2016-10-20
9       J  2017-01-31
10      K  2017-05-01
11      L  2017-07-25
12      M  2017-10-24
13      N  2018-01-30
14      O  2018-04-25
15      P  2018-07-25
16      Q  2018-10-24
17      R  2019-01-29
18      S  2019-04-30
19      T  2019-07-30
20      U  2019-10-29
21      V  2020-01-28
22      W  2020-04-28
23      X  2020-07-28
24      Y  2020-10-27
25      Z  2021-01-26